-- MySQL Script generated by MySQL Workbench
-- Sat Oct 17 12:25:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pupuseria_Final
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pupuseria_Final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pupuseria_Final` DEFAULT CHARACTER SET utf8 ;
USE `Pupuseria_Final` ;

-- -----------------------------------------------------
-- Table `Pupuseria_Final`.`Direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pupuseria_Final`.`Direcciones` (
  `Cod_direc` INT NOT NULL AUTO_INCREMENT,
  `Municipio` VARCHAR(30) NOT NULL,
  `Direccion` VARCHAR(40) NOT NULL,
  `Punto_referen` VARCHAR(25) NOT NULL,
  `Telefono` INT(8) NOT NULL,
  PRIMARY KEY (`Cod_direc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pupuseria_Final`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pupuseria_Final`.`Usuarios` (
  `Cod_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Prim_nom` VARCHAR(25) NOT NULL,
  `Seg_nom` VARCHAR(25) NULL,
  `Prim_ape` VARCHAR(25) NOT NULL,
  `Seg_ape` VARCHAR(25) NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(10) NOT NULL,
  `cod_direc` INT NOT NULL,
  PRIMARY KEY (`Cod_Usuario`),
  CONSTRAINT `fk_cod_direcciones`
    FOREIGN KEY (`cod_direc`)
    REFERENCES `Pupuseria_Final`.`Direcciones` (`Cod_direc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pupuseria_Final`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pupuseria_Final`.`Empleados` (
  `Cod_Empleado` INT NOT NULL AUTO_INCREMENT,
  `Prim_nom` VARCHAR(25) NOT NULL,
  `Seg_nom` VARCHAR(25) NULL,
  `Prim_ape` VARCHAR(25) NOT NULL,
  `Seg_ape` VARCHAR(25) NULL,
  `Email` VARCHAR(20) NOT NULL,
  `Contraseña` VARCHAR(10) NOT NULL,
  `Foto` BLOB NOT NULL,
  PRIMARY KEY (`Cod_Empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pupuseria_Final`.`Postres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pupuseria_Final`.`Postres` (
  `Cod_postre` INT NOT NULL AUTO_INCREMENT,
  `tipo_postre` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`Cod_postre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pupuseria_Final`.`Ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pupuseria_Final`.`Ingredientes` (
  `Cod_Ingre` INT NOT NULL AUTO_INCREMENT,
  `Ingredientes` VARCHAR(35) NOT NULL,
  `Costo_Indiv` FLOAT NOT NULL,
  PRIMARY KEY (`Cod_Ingre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pupuseria_Final`.`Bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pupuseria_Final`.`Bebidas` (
  `Cod_Bebida` INT NOT NULL AUTO_INCREMENT,
  `Tipo_bebida` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`Cod_Bebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pupuseria_Final`.`Pupusas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pupuseria_Final`.`Pupusas` (
  `Cod_Pupusa` INT NOT NULL AUTO_INCREMENT,
  `Harina` VARCHAR(10) NOT NULL,
  `Cod_Ingre` INT NOT NULL,
  PRIMARY KEY (`Cod_Pupusa`),
  CONSTRAINT `fk_cod_ingre`
    FOREIGN KEY (`Cod_Ingre`)
    REFERENCES `Pupuseria_Final`.`Ingredientes` (`Cod_Ingre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pupuseria_Final`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pupuseria_Final`.`Productos` (
  `Cod_Produc` INT NOT NULL AUTO_INCREMENT,
  `Cod_Pupusa` INT NOT NULL,
  `Cod_Postre` INT NOT NULL,
  `Cod_Bebida` INT NOT NULL,
  `PrecioProducto` FLOAT NOT NULL,
  `Descripcion` VARCHAR(35) NOT NULL,
  `Foto` BLOB NOT NULL,
  PRIMARY KEY (`Cod_Produc`),
  CONSTRAINT `fk_cod_pupusa1`
    FOREIGN KEY (`Cod_Pupusa`)
    REFERENCES `Pupuseria_Final`.`Pupusas` (`Cod_Pupusa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cod_postre1`
    FOREIGN KEY (`Cod_Postre`)
    REFERENCES `Pupuseria_Final`.`Postres` (`Cod_postre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cod_bebida1`
    FOREIGN KEY (`Cod_Bebida`)
    REFERENCES `Pupuseria_Final`.`Bebidas` (`Cod_Bebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pupuseria_Final`.`Ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pupuseria_Final`.`Ordenes` (
  `Cod_Orden` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(35) NOT NULL,
  `Cod_Usuario` INT NOT NULL,
  `CreadaEl` DATE NOT NULL,
  PRIMARY KEY (`Cod_Orden`),
  CONSTRAINT `fk_cod_usuario2`
    FOREIGN KEY (`Cod_Usuario`)
    REFERENCES `Pupuseria_Final`.`Usuarios` (`Cod_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pupuseria_Final`.`Detalle_Ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pupuseria_Final`.`Detalle_Ordenes` (
  `Cod_Orden` INT NOT NULL,
  `Cod_Producto` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Descuento` FLOAT NOT NULL,
  PRIMARY KEY (`Cod_Orden`),
  CONSTRAINT `fk_cod_ordendet1`
    FOREIGN KEY (`Cod_Orden`)
    REFERENCES `Pupuseria_Final`.`Ordenes` (`Cod_Orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cod_producto1`
    FOREIGN KEY (`Cod_Producto`)
    REFERENCES `Pupuseria_Final`.`Productos` (`Cod_Produc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
